repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  javax_annotation: com.google.code.findbugs:jsr305:jar:2.0.1
  gwt_user: com.google.gwt:gwt-user:jar:2.5.1

  # Mocking library used in tests
  mockito: org.mockito:mockito-all:jar:1.9.5
