repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  jsinterop_base: com.google.jsinterop:base:jar:1.0.0-RC1

  elemental2_core: org.realityforge.com.google.elemental2:elemental2-core:jar:1.0.0-b16-6897368
  elemental2_dom: org.realityforge.com.google.elemental2:elemental2-dom:jar:1.0.0-b16-6897368
  elemental2_promise: org.realityforge.com.google.elemental2:elemental2-promise:jar:1.0.0-b16-6897368

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.0
  gwt_user: com.google.gwt:gwt-user:jar:2.8.2
  gwt_dev: com.google.gwt:gwt-dev:jar:2.8.2

  # Mocking library used in tests
  mockito: org.mockito:mockito-all:jar:1.9.5

  javaee: javax:javaee-api:jar:7.0
